[tool.poetry]
name = "hoshy"
version = "0.210317.0"
description = "Cryptographic hash (half-blake3) and operators - see package hosh for a faster, native (compiled) approach"
authors = ["davips <dpsabc@gmail.com>"]
license = "GPL"
readme = 'README.md'
packages = [
    { include = "hosh", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.8"
blake3 = "^0.1.8"
colored = "^1.4.2"
numpy = "^1.20.1"

[tool.poetry.dev-dependencies]
autoreadme = "^0.2102.20"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
