[tool.poetry]
name = "garoupa"
version = "1.210630.0"
description = "Cryptographic hash, abstract algebra and operators"
authors = ["davips <dpsabc@gmail.com>"]
license = "GPL"
readme = 'README.md'
packages = [
    { include = "garoupa", from = "src" },
]

# For more dependencies and faster execution: poetry install -E full
[tool.poetry.extras]
full = ["progress", "pathos", "numpy", "hosh"]

[tool.poetry.dependencies]
python = "^3.8"
wheel = "^0.36.2"
blake3 = "^0.1.8"
colored = "^1.4.2"
progress = { version = "^1.5", optional = true }
pathos = { version = "^0.2.7", optional = true }
numpy = { version = "^1.20.1", optional = true }
hosh = { version = "^0.210317.0", optional = true }
sympy = "^1.8"

[tool.poetry.dev-dependencies]
autoreadme = "^0.2102.20"
pytest = "^6.2.2"
pytest-cov = "^2.11.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

# [[tool.poetry.source]]
# name = "dvpypi"
# url = "http://localhost:8080/simple"
